name: sabumi3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bg.jpg
    - assets/bgds.jpg
    - assets/bgds2.png
    - assets/savilage.jpeg
    - assets/savilage.png
    - assets/kamar.jpg
    - assets/tenda.png
    - assets/bumi_aki.png
    - assets/menu1.png
    - assets/menu2.png
    - assets/sop_iga.png
    - assets/gurame.png
    - assets/lemon_tea.png
    - assets/ayambakar.png
    - assets/nasiliwet.png
    - assets/surabi.png
    - assets/mojito.png
    - assets/profile.png
    - assets/kamar_superior.png
    - assets/tenda_keong.png
    - assets/tenda_dome.png
  fonts:
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada-Regular.ttf
    - family: LeckerliOne
      fonts:
        - asset: assets/fonts/LeckerliOne-Regular.ttf
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
